### PR TITLE
r2158 changelog

### PR DESCRIPTION
**Pull request by ChxseH**

### CODE REVIEW

**Review by 3ldor — COMMENTED** [review]
Isn't it redundant to state "no changes"? Shouldn't it be pretty clear no changes were made to the other games if they're left out?

**Comment by ChxseH** [comment]
> Isn't it redundant to state "no changes"?

Probably, just going off of what previous changelogs had. Can change if you want.

**Comment by 3ldor** [comment]
> > Isn't it redundant to state "no changes"?
> 
> Probably, just going off of what previous changelogs had. Can change if you want.

I think it's better to keep the changelogs short and straight to the point. Some of the older entries also mention the launcher, but then stopped at some point - so not super consistent.

**Comment by ChxseH** [comment]
Will go ahead and remove every mention then. Will be in this PR.

**Comment by ChxseH** [comment]
> Will go ahead and remove every mention then. Will be in this PR.

Done in c7a70b8.

**Review by 3ldor — APPROVED** [review]

**Pull request merged**
